# Grafana IoT Workshop Config File
# Replace all the things in <> below
# Do not change the DEVICE_NAME or your dashboard won't work

CIRCUITPY_WIFI_SSID = "<WIFI_SSID>"
CIRCUITPY_WIFI_PASSWORD = "<WIFI_PASSWORD>"
GRAFANA_GRAPHITE_URL = "https://<YOURENDPOINTURL>/graphite/metrics"
GRAFANA_API_KEY = "<YOURAPIKEY>"
GRAFANA_USER = "<YOURUSERNAME>"
CIRCUITPY_WEB_API_PASSWORD = "grafana"
CIRCUITPY_WEB_API_PORT = 80
DEVICE_NAME = "atoms3"
DEVICE_LOCATION = "office"